import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ShopProvider from "../context/shopContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ShopProvider>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </ShopProvider>
  );
}
